### PR TITLE
Add function setState() to use own redirect state

### PR DESCRIPTION
**Pull request by staypekos**
Using own state allow to redirect to the page which was requested before logging in.

### CODE REVIEW

**Comment by staypekos** [comment]
Any progress? Thanks

**Comment by venca-x** [comment]
Merged, Thanks

**Comment by venca-x** [comment]
I released v1.0.7

**Comment by staypekos** [comment]
Thanks a lot

**Comment by venca-x** [comment]
@staypekos can you please add pull request with example use that? Add to README.md?

**Comment by staypekos** [comment]
Sure, I've done it in #7

**Pull request merged**
